### ISSUE TITLE
error: Cannot read property 'options' of undefined

### ISSUE THREAD

**Issue by zdenekgebauer** [lando/vuepress-theme-default-plus#43]
ERROR ==> problem loading plugin @lando/vuepress-theme-default-plus from C:/snapshot/cli/node_modules/@lando/vuepress-theme-default-plus/index.js: TypeError: Cannot read property 'options' of undefined
    at C:\snapshot\cli\node_modules\@lando\vuepress-theme-default-plus\index.js
    at Plugins.load (C:\snapshot\cli\lib\plugins.js)
    at C:\snapshot\cli\lib\lando.js
    at Array.map (<anonymous>)
    at bootstrapConfig (C:\snapshot\cli\lib\lando.js)
    at bootstrapRouter (C:\snapshot\cli\lib\lando.js)
    at C:\snapshot\cli\lib\lando.js
    at tryCatcher (C:\snapshot\cli\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\snapshot\cli\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (C:\snapshot\cli\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (C:\snapshot\cli\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (C:\snapshot\cli\node_modules\bluebird\js\release\promise.js:729:18)
    at Promise._fulfill (C:\snapshot\cli\node_modules\bluebird\js\release\promise.js:673:18)
    at Promise._resolveCallback (C:\snapshot\cli\node_modules\bluebird\js\release\promise.js:466:57)
    at Promise._settlePromiseFromHandler (C:\snapshot\cli\node_modules\bluebird\js\release\promise.js:559:17)
    at Promise._settlePromise (C:\snapshot\cli\node_modules\bluebird\js\release\promise.js:604:18)

occurs with lando 3.6.4 on windows 
excerpt from lando.yml:
```
recipe: lamp
excludes:
    - node_modules
````

**Comment by labboy0276** [comment]
@zdenekgebauer please see https://github.com/lando/lando/issues/3384

Closing this out since we already have a ticket on it in the main lando repo.
